### ISSUE TITLE
mpi4py fails to build - uses system cython

### ISSUE THREAD

**Issue by johannesring** [hashdist/hashstack#583]
```
2014/12/09 18:02:56 - INFO: [package:run_job] running install
2014/12/09 18:02:56 - INFO: [package:run_job] running build
2014/12/09 18:02:56 - INFO: [package:run_job] running build_src
2014/12/09 18:02:56 - INFO: [package:run_job] cythonizing
'mpi4py.MPI.pyx' -> 'mpi4py.MPI.c' 2014/12/09 18:02:56 - INFO:
[package:run_job] Traceback (most recent call last): 2014/12/09
18:02:56 - INFO: [package:run_job]   File "setup.py", line 624, in
<module> 2014/12/09 18:02:56 - INFO: [package:run_job]     main()
2014/12/09 18:02:56 - INFO: [package:run_job]   File "setup.py", line
621, in main 2014/12/09 18:02:56 - INFO: [package:run_job]
run_setup() 2014/12/09 18:02:56 - INFO: [package:run_job]   File
"setup.py", line 493, in run_setup 2014/12/09 18:02:56 - INFO:
[package:run_job]     **metadata) 2014/12/09 18:02:56 - INFO:
[package:run_job]   File
"/srv/groot/blechta/.hashdist/tmp/mpi4py-dps5vsljzl7g-1/conf/mpidistutils.py",
line 441, in setup 2014/12/09 18:02:56 - INFO: [package:run_job]
return fcn_setup(**attrs) 2014/12/09 18:02:56 - INFO:
[package:run_job]   File
"/srv/groot/blechta/.hashdist/bld/python/ctzx2dm36c6d/lib/python2.7/distutils/core.py",
line 151, in setup 2014/12/09 18:02:56 - INFO: [package:run_job]
dist.run_commands() 2014/12/09 18:02:56 - INFO: [package:run_job]
File
"/srv/groot/blechta/.hashdist/bld/python/ctzx2dm36c6d/lib/python2.7/distutils/dist.py",
line 953, in run_commands 2014/12/09 18:02:56 - INFO:
[package:run_job]     self.run_command(cmd) 2014/12/09 18:02:56 - INFO:
[package:run_job]   File
"/srv/groot/blechta/.hashdist/bld/python/ctzx2dm36c6d/lib/python2.7/distutils/dist.py",
line 972, in run_command 2014/12/09 18:02:56 - INFO:
[package:run_job]     cmd_obj.run() 2014/12/09 18:02:56 - INFO:
[package:run_job]   File
"/srv/groot/blechta/.hashdist/bld/python/ctzx2dm36c6d/lib/python2.7/distutils/command/install.py",
line 563, in run 2014/12/09 18:02:56 - INFO: [package:run_job]
self.run_command('build') 2014/12/09 18:02:56 - INFO:
[package:run_job]   File
"/srv/groot/blechta/.hashdist/bld/python/ctzx2dm36c6d/lib/python2.7/distutils/cmd.py",
line 326, in run_command 2014/12/09 18:02:56 - INFO:
[package:run_job]     self.distribution.run_command(command) 2014/12/09
18:02:56 - INFO: [package:run_job]   File
"/srv/groot/blechta/.hashdist/bld/python/ctzx2dm36c6d/lib/python2.7/distutils/dist.py",
line 972, in run_command 2014/12/09 18:02:56 - INFO:
[package:run_job]     cmd_obj.run() 2014/12/09 18:02:56 - INFO:
[package:run_job]   File
"/srv/groot/blechta/.hashdist/bld/python/ctzx2dm36c6d/lib/python2.7/distutils/command/build.py",
line 127, in run 2014/12/09 18:02:56 - INFO: [package:run_job]
self.run_command(cmd_name) 2014/12/09 18:02:56 - INFO:
[package:run_job]   File
"/srv/groot/blechta/.hashdist/bld/python/ctzx2dm36c6d/lib/python2.7/distutils/cmd.py",
line 326, in run_command 2014/12/09 18:02:56 - INFO:
[package:run_job]     self.distribution.run_command(command) 2014/12/09
18:02:56 - INFO: [package:run_job]   File
"/srv/groot/blechta/.hashdist/bld/python/ctzx2dm36c6d/lib/python2.7/distutils/dist.py",
line 972, in run_command 2014/12/09 18:02:56 - INFO:
[package:run_job]     cmd_obj.run() 2014/12/09 18:02:56 - INFO:
[package:run_job]   File "setup.py", line 594, in build_sources
2014/12/09 18:02:56 - INFO: [package:run_job]     wdir='src',
force=cmd.force, VERSION=CYTHON) 2014/12/09 18:02:56 - INFO:
[package:run_job]   File "setup.py", line 573, in run_cython 2014/12/09
18:02:56 - INFO: [package:run_job]     wdir=wdir) 2014/12/09 18:02:56 -
INFO: [package:run_job]   File
"/srv/groot/blechta/.hashdist/tmp/mpi4py-dps5vsljzl7g-1/conf/cythonize.py",
line 9, in cythonize 2014/12/09 18:02:56 - INFO: [package:run_job]
from Cython.Compiler.Main import \ 2014/12/09 18:02:56 - INFO:
[package:run_job]   File
"/usr/lib/pymodules/python2.7/Cython/Compiler/Main.py", line 18, in
<module> 2014/12/09 18:02:56 - INFO: [package:run_job]     import Code
2014/12/09 18:02:56 - INFO: [package:run_job]
ImportError: /usr/lib/pymodules/python2.7/Cython/Compiler/Code.so:
undefined symbol: PyUnicodeUCS4_DecodeUTF8 2014/12/09 18:02:56 - ERROR:
[package:run_job] Command '[u'/bin/bash', '_hashdist/build.sh']'
returned non-zero exit status 1 2014/12/09 18:02:56 - ERROR:
[package:run_job] command failed (code=1); raising
```

**Comment by johannesring** [comment]
A similar problem was [reported](http://fenicsproject.org/pipermail/fenics/2015-February/002481.html) today. @ahmadia - have you looked at this? Do you know how to fix it?

**Comment by ahmadia** [comment]
The idea I had in mind was to add a flag to our Python build recipes (setuptools/distutils) that tells Python not to search in user directories. Per [PEP 370](https://www.python.org/dev/peps/pep-0370/#implementation)

> The user site directory can be suppressed with a new option -s or the environment variable PYTHONNOUSERSITE . The feature can be disabled globally by setting site.ENABLE_USER_SITE to the value False . It must be set by editing site.py . It can't be altered in sitecustomize.py or later. 

This should probably be set off by default in our Python install.
