### ISSUE TITLE
FEniCS linking broken on Darwin

### ISSUE THREAD

**Issue by alogg** [hashdist/hashstack#593]
When building FEniCS with HashStack on Mac OS X Yosemite 10.10.1, I get the following error when trying to import a FEniCS Python module after a seemingly successful build with HashStack/HashDist:

    $ python -c "import dolfin"
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/Users/logg/.hashdist/bld/profile/3cy7e2il6iie/lib/python2.7/site-packages/dolfin/__init__.py", line 16, in <module>
    from . import cpp
    File "/Users/logg/.hashdist/bld/profile/3cy7e2il6iie/lib/python2.7/site-packages/dolfin/cpp/__init__.py", line 42, in <module>
    exec("from . import %s" % module_name)
    File "<string>", line 1, in <module>
    File "/Users/logg/.hashdist/bld/profile/3cy7e2il6iie/lib/python2.7/site-packages/dolfin/cpp/common.py", line 32, in <module>
    _common = swig_import_helper()
    File "/Users/logg/.hashdist/bld/profile/3cy7e2il6iie/lib/python2.7/site-packages/dolfin/cpp/common.py", line 28, in swig_import_helper
    _mod = imp.load_module('_common', fp, pathname, description)
    ImportError: dlopen(/Users/logg/.hashdist/bld/profile/3cy7e2il6iie/lib/python2.7/site-packages/dolfin/cpp/_common.so, 2): Library not loaded: libdolfin.1.4.dylib
    Referenced from: /Users/logg/.hashdist/bld/profile/3cy7e2il6iie/lib/python2.7/site-packages/dolfin/cpp/_common.so
    Reason: image not found

**Comment by johannesring** [comment]
Fixed in #861.
