### ISSUE TITLE
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by johannesring** [hashdist/hashstack#781]
I have successfully built FEniCS with Hashdist on a cluster in Sweden, but when I try to import dolfin in Python I get the following error:

    $ python -c "import dolfin"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/johannr/src/hashstack/fenics-1.5.0.alarik.lunarc.gnu/lib/python2.7/site-packages/dolfin/__init__.py", line 16, in <module>
        from . import cpp
      File "/home/johannr/src/hashstack/fenics-1.5.0.alarik.lunarc.gnu/lib/python2.7/site-packages/dolfin/cpp/__init__.py", line 42, in <module>
        exec("from . import %s" % module_name)
      File "<string>", line 1, in <module>
      File "/home/johannr/src/hashstack/fenics-1.5.0.alarik.lunarc.gnu/lib/python2.7/site-packages/dolfin/cpp/common.py", line 32, in <module>
        _common = swig_import_helper()
      File "/home/johannr/src/hashstack/fenics-1.5.0.alarik.lunarc.gnu/lib/python2.7/site-packages/dolfin/cpp/common.py", line 28, in swig_import_helper
        _mod = imp.load_module('_common', fp, pathname, description)
    ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory

It turns out that the rpath has not been set correctly in the Boost iostreams library:

    $ ldd /alarik/nobackup/i_p/johannr/.hashdist/bld/boost/y7he5zxfcmvv/lib/libboost_iostreams.so.1.55.0 | grep bz2
    	libbz2.so.1.0 => not found

However, it is set correctly in the symbolic link:

    $ ldd /alarik/nobackup/i_p/johannr/.hashdist/bld/boost/y7he5zxfcmvv/lib/libboost_iostreams.so | grep bz2
    	libbz2.so.1.0 => /alarik/nobackup/i_p/johannr/.hashdist/bld/boost/y7he5zxfcmvv/lib/../../../bzip2/ydfav75zjrep/lib/libbz2.so.1.0 (0x00007fbc8f200000)

But this is not a symbolic link as it should be:

    $ ls -l /alarik/nobackup/i_p/johannr/.hashdist/bld/boost/y7he5zxfcmvv/lib/libboost_iostreams.so*
    -r-xr-xr-x 1 johannr lu-jhsimu 160312 May 19 12:20 /alarik/nobackup/i_p/johannr/.hashdist/bld/boost/y7he5zxfcmvv/lib/libboost_iostreams.so
    -r-xr-xr-x 1 johannr lu-jhsimu 160176 May 19 12:20 /alarik/nobackup/i_p/johannr/.hashdist/bld/boost/y7he5zxfcmvv/lib/libboost_iostreams.so.1.55.0

The problem is in `boost.yaml`, where we run patchelf on the symbolic links instead of the actual library files. This turns them into copies instead of symbolic links. I will make a PR that fixes this problem.

**Comment by certik** [comment]
Great catch and analysis, didn't realize this issue before.

**Comment by johannesring** [comment]
Thanks, fixed in #782.
