### ISSUE TITLE
python.yaml fails on ArchLinux

### ISSUE THREAD

**Issue by dajuno** [hashdist/hashstack#862]
Hi,
I'm trying to build fenics using almost the default fenics.Linux.yaml (just added scipy and pip).
However, ```hit build``` gives 
[ERROR] /home/david/dev/hashstack/pkgs/python/python.yaml, line 62: illegal mode: update

and ```hit build pkgs/python/python.yaml```:

[ERROR] Uncaught exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/hashdist/cli/main.py", line 173, in help_on_exceptions
    return func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/hashdist/cli/main.py", line 147, in command_line_entry_point
    retcode = args.subcommand_handler(ctx, args)
  File "/usr/lib/python2.7/site-packages/hashdist/cli/frontend_cli.py", line 40, in run
    self = cls(ctx, args)
  File "/usr/lib/python2.7/site-packages/hashdist/cli/frontend_cli.py", line 35, in __init__
    self.profile = load_profile(self.ctx.logger, self.checkouts, args.profile)
  File "/usr/lib/python2.7/site-packages/hashdist/spec/profile.py", line 481, in load_profile
    doc = load_and_inherit_profile(checkout_manager, profile_file)
  File "/usr/lib/python2.7/site-packages/hashdist/spec/profile.py", line 436, in load_and_inherit_profile
    for parent_include_doc in doc['extends']]
  File "/usr/lib/python2.7/site-packages/hashdist/spec/profile.py", line 427, in load_and_inherit_profile
    profile_file = resolve_profile(cwd, include_doc['file'])
TypeError: string indices must be integers

Any hints? I'm new to hashdist, procedure was: install hashdist with pip into python2 (on Arch python3 is standard), git clone hashdist, edit default.yaml and hit build.

Thanks

**Comment by ahmadia** [comment]
I don't know when we last updated the pip repository.  I would `git clone` the hashdist repository.  Also, you can't build packages on their own, but you can specify a one-package profile.

**Comment by dajuno** [comment]
I see. It works with the git version, thanks! :)
