### ISSUE TITLE
matplotlib import fails - ImportError: libpng16.so.16: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by johannesring** [hashdist/hashstack#863]
``` console
$ python -c "from matplotlib import pyplot"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usit/abel/u1/johannr/src/hashstack-2015-10-05/fenics-1.6.0.abel.gnu/lib/python2.7/site-packages/matplotlib/pyplot.py", line 27, in <module>
    import matplotlib.colorbar
  File "/usit/abel/u1/johannr/src/hashstack-2015-10-05/fenics-1.6.0.abel.gnu/lib/python2.7/site-packages/matplotlib/colorbar.py", line 34, in <module>
    import matplotlib.collections as collections
  File "/usit/abel/u1/johannr/src/hashstack-2015-10-05/fenics-1.6.0.abel.gnu/lib/python2.7/site-packages/matplotlib/collections.py", line 27, in <module>
    import matplotlib.backend_bases as backend_bases
  File "/usit/abel/u1/johannr/src/hashstack-2015-10-05/fenics-1.6.0.abel.gnu/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 56, in <module>
    import matplotlib.textpath as textpath
  File "/usit/abel/u1/johannr/src/hashstack-2015-10-05/fenics-1.6.0.abel.gnu/lib/python2.7/site-packages/matplotlib/textpath.py", line 22, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/usit/abel/u1/johannr/src/hashstack-2015-10-05/fenics-1.6.0.abel.gnu/lib/python2.7/site-packages/matplotlib/mathtext.py", line 63, in <module>
    import matplotlib._png as _png
ImportError: libpng16.so.16: cannot open shared object file: No such file or directory
```

Setting the correct rpath fixes this problem.

**Comment by johannesring** [comment]
Fixed in f3185f0d70977bcaeacfca26286e45543ed61d4c.
