### ISSUE TITLE
jasper missing in pillow yaml file

### ISSUE THREAD

**Issue by robertsawko** [hashdist/hashstack#927]
It seems that `pillow` cannot see JPEG2000 codecs.

```
[pillow] Traceback (most recent call last):
[pillow]   File "<string>", line 1, in <module>
[pillow]   File "<string>", line 760, in <module>
[pillow]   File "/home/robert/.hashdist/bld/python/bdccyvxhqdm7/lib/python2.7/distutils/core.py", line 151, in setup
[pillow]     dist.run_commands()
[pillow]   File "/home/robert/.hashdist/bld/python/bdccyvxhqdm7/lib/python2.7/distutils/dist.py", line 953, in run_commands
[pillow]     self.run_command(cmd)
[pillow]   File "/home/robert/.hashdist/bld/python/bdccyvxhqdm7/lib/python2.7/distutils/dist.py", line 972, in run_command
[pillow]     cmd_obj.run()
[pillow]   File "/home/robert/.hashdist/bld/python/bdccyvxhqdm7/lib/python2.7/distutils/command/build_ext.py", line 337, in run
[pillow]     self.build_extensions()
[pillow]   File "<string>", line 507, in build_extensions
[pillow] ValueError: --enable-jpeg2000 requested but jpeg2000 not found, aborting.
[pillow|ERROR] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 1
[pillow|ERROR] command failed (code=1); raising
```

I've already added `jasper` to `build` in yaml file and added the include and lib directories, but that has not resolved it.

**Comment by robertsawko** [comment]
I really cannot figure out what's going wrong here. For now I removed the `--enable-jpeg2000` flag and it got passed it, but I am afraid I will lose some functionality and it will hit me back later.

It seems that the compilation of `pillow` is executed from within Python, so it must be that `setup.py` or a related script doesn't carry over the information about `jasper`.

**Comment by cekees** [comment]
It looks like grib_api and pillow need different versions of openjpeg.  grib_api needs 1.5 or earlier  whereas pillow works with openjpeg 2.1. I looked more closely at why things work  on my machine, and it's because I use openjpeg 2.1 in hashstack but the grib_api configure script is finding openjpeg 1.5 on my system.  For now I would just try things without jpeg support  in pillow.

**Comment by robertsawko** [comment]
Yes, I can confirm that if I install openjpeg2 on my system, pillow works. I was mislead into thinking that it's due to jasper. I am installing on a very fresh system, so it doesn't have very many things installed. It's a bit of a test for hashdist. Wouldn't it be just enough then to actually create a separate package openjpeg2 and add it as dependency?

**Comment by cekees** [comment]
Yes, that  would work.  I was just trying to eliminate possible  sources  of confusion with multiple openjpeg  packages, but I don't see a good way around it.
